workflows:
  android-apk:
    name: Android APK
    max_build_duration: 60

    environment:
      flutter: 3.44.0

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk


  ios-app-store:
    name: iOS App Store
    max_build_duration: 120

    integrations:
      app_store_connect: RMHealth

    environment:
      flutter: 3.44.0
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cartzlinkv2.icare

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Set up iOS code signing
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false