 - name: Install Flutter dependencies
          run: flutter pub get

        - name: Build release APK
          run: flutter build apk --release --no-tree-shake-icons

        - name: Rename APK
          run: |
            mkdir -p output
            cp build/app/outputs/flutter-apk/app-release.apk \
               output/iCare-$(date +'%Y%m%d-%H%M').apk

        - name: Upload APK
          uses: actions/upload-artifact@v4
          with:
            name: iCare-APK-${{ github.run_number }}
            path: output/*.apk
            retention-days: 30
